# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

def shared_pods_for_testing
  pod 'Quick', '~> 6.1.0'
  pod 'Nimble', '~> 11.2.1'
end

target 'DMErrorHandlingPodExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'DMErrorHandling', path: '../../DMErrorHandling/'

  # Pods for DMErrorHandlingPodExample

  target 'DMErrorHandlingPodExampleTests' do
    inherit! :search_paths
    
    shared_pods_for_testing
  end

  target 'DMErrorHandlingPodExampleUITests' do
    shared_pods_for_testing
  end

end
